import nodemailer from "nodemailer";

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

export function magicLinkEmail(link: string) {
  const safeLink = escapeHtml(link);
  return {
    subject: "Entrar no RPG English Learning",
    text: `Olá, aventureiro!\n\nRecebemos uma solicitação de login para sua conta. Use este link para acessar sua jornada:\n${link}\n\nSe você não solicitou, por favor ignore esta mensagem.\n\nRPG English Learning`,
    html: `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><title>Entrar no RPG English Learning</title><style>body{margin:0;padding:0;width:100%!important;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}.link-texto{color:#2563eb;text-decoration:underline;word-break:break-all}@media (prefers-color-scheme:dark){body,.body-bg{background-color:#18181b!important}.content-bg{background-color:#27272a!important}h1,h2,p,span{color:#f4f4f5!important}.footer-text{color:#a1a1aa!important}}</style></head><body class="body-bg" style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background-color:#f4f4f5;margin:0;padding:0"><div style="display:none;max-height:0;overflow:hidden">Use este link para acessar sua conta no RPG English Learning sem senha.</div><table role="presentation" width="100%"><tr><td align="center" style="padding:40px 20px"><table role="presentation" width="100%" style="max-width:600px;background-color:#ffffff;border-radius:8px;border:1px solid #e4e4e7;overflow:hidden" class="content-bg"><tr><td style="padding:30px 40px;background-color:#000000;text-align:center"><h1 style="color:#ffffff;margin:0;font-size:24px;font-weight:700">RPG English Learning</h1></td></tr><tr><td style="padding:40px 40px 20px"><h2 style="color:#18181b;margin-top:0;margin-bottom:20px;font-size:20px">Olá, aventureiro!</h2><p style="color:#3f3f46;font-size:16px;line-height:26px;margin-bottom:30px">Recebemos uma solicitação de login para sua conta. Clique no botão abaixo para acessar sua jornada:</p><table role="presentation" style="margin-bottom:30px;width:100%"><tr><td align="center"><a href="${safeLink}" target="_blank" style="display:inline-block;padding:16px 32px;background-color:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:16px;border-radius:6px">Entrar no Sistema</a></td></tr></table><p style="color:#71717a;font-size:14px;line-height:22px;margin-top:30px;border-top:1px solid #e4e4e7;padding-top:20px">Se o botão acima não funcionar, copie e cole o link abaixo no seu navegador:<br><br><a href="${safeLink}" class="link-texto" style="color:#2563eb;font-size:12px">${safeLink}</a></p></td></tr></table><table role="presentation" width="100%" style="max-width:600px"><tr><td style="padding:20px;text-align:center"><p class="footer-text" style="color:#a1a1aa;font-size:12px;line-height:18px;margin:0">Este email foi enviado automaticamente para confirmar seu acesso.<br>Se você não solicitou, por favor ignore esta mensagem.<br><br><strong>RPG English Learning</strong></p></td></tr></table></td></tr></table></body></html>`,
  };
}

export async function sendMagicLink(email: string, link: string) {
  const transporter = nodemailer.createTransport({ host: process.env.SMTP_SERVER, port: Number(process.env.SMTP_PORT ?? 587), secure: Number(process.env.SMTP_PORT) === 465, auth: process.env.SMTP_LOGIN ? { user: process.env.SMTP_LOGIN, pass: process.env.SMTP_KEY } : undefined, connectionTimeout: Number(process.env.SMTP_TIMEOUT_SECONDS ?? 10) * 1000 });
  await transporter.sendMail({ from: process.env.SMTP_FROM_EMAIL ? `${process.env.SMTP_FROM_NAME ?? "RPG English Learning"} <${process.env.SMTP_FROM_EMAIL}>` : undefined, to: email, ...magicLinkEmail(link) });
}
